navigation:
  - title: Etusivu
    url: /index.html

  - title: Ilmoittautuminen
    url: /register/index.html

  - title: Hinnat
    url: /prices/index.html

  - title: Ohjelma
    url: /program/index.html

  - title: Yhteystiedot
    url: /contact/index.html

graphics:
  - name: TR15_julistepohja
    url: /graphics/TR15_juliste.png
    description: Julistepohja, sisältää yleisen pohjan mutta ei tarkempia tietoja.

  - name: Teekkariristeily_2015_Esimerkkijuliste
    url: /graphics/TR15_juliste_esimerkki.png
    description: Esimerkki mainosjulisteesta.
