navigation:
  - title: Etusivu
    url: /index.html

  - title: Ilmoittautuminen
    url: /register/index.html

  - title: Hinnat
    url: /prices/index.html

  - title: Ohjelma
    url: /index.html

  - title: Yhteystiedot
    url: /index.html
